import type { CourseDetail } from "@/features/student/types/course-detail";

// ─────────────────────────────────────────────────────────
// Realistic mock data for the course detail page
// ─────────────────────────────────────────────────────────

export const MOCK_COURSE: CourseDetail = {
  id: "acca-f1-ab",
  title: "ACCA F1 — Accountant in Business",
  description:
    "Master the foundational principles of business organisation, stakeholder management, and corporate governance required for the ACCA qualification.",
  thumbnail: "/placeholder-course.jpg",
  level: "Foundation",
  category: "ACCA",
  duration: "42 hours",
  language: "English",
  rating: 4.7,
  studentsCount: 2_340,
  lessonsCount: 86,
  modulesCount: 8,
  assignmentsCount: 12,
  resourcesCount: 34,
  progress: 38,
  lastLesson: "Stakeholder Analysis Frameworks",
  certificateStatus: "in_progress",
  about:
    "This course covers the ACCA F1 (Accountant in Business) syllabus in full. You'll study the purpose and types of business organisations, the role of stakeholders, external environmental factors, corporate governance principles, and the professional accountant's role in business. The curriculum follows the latest ACCA syllabus and is designed to give you exam-ready confidence through structured lectures, quizzes, and practice assignments.",
  learningOutcomes: [
    "Understand the purpose and types of business organisations",
    "Analyse stakeholder needs and manage stakeholder relationships",
    "Evaluate the impact of the external environment on business",
    "Apply corporate governance and ethical principles",
    "Describe the role of accounting and finance in organisations",
    "Prepare for the ACCA F1 examination with practice questions",
  ],
  courseIncludes: [
    "42 hours of video lectures",
    "86 lessons across 8 modules",
    "12 graded assignments",
    "34 downloadable resources",
    "Certificate of completion",
    "Lifetime access",
  ],
  accessInfo: "Full lifetime access",
  instructor: {
    id: "inst-001",
    name: "Dr. Sarah Mitchell",
    avatar: "",
    title: "ACCA Fellow · Senior Lecturer",
    bio: "Dr. Mitchell has over 15 years of experience teaching ACCA courses. She holds a PhD in Accounting from the University of Edinburgh and has trained over 10,000 students globally with a 95% first-time pass rate.",
    coursesCount: 12,
    studentsCount: 10_450,
    rating: 4.8,
  },
  modules: [
    {
      id: "mod-1",
      title: "Introduction to Business Organisations",
      lessonsCount: 10,
      duration: "5h 20m",
      lessons: [
        { id: "l-1-1", title: "What is a Business Organisation?", duration: "32 min", type: "video", status: "completed" },
        { id: "l-1-2", title: "Types of Business Entity", duration: "28 min", type: "video", status: "completed" },
        { id: "l-1-3", title: "Business Purpose and Objectives", duration: "35 min", type: "video", status: "completed" },
        { id: "l-1-4", title: "Reading: Organisation Structures", duration: "15 min", type: "reading", status: "completed" },
        { id: "l-1-5", title: "Quiz: Business Organisations", duration: "10 min", type: "quiz", status: "completed" },
        { id: "l-1-6", title: "Organisational Culture", duration: "30 min", type: "video", status: "completed" },
        { id: "l-1-7", title: "Committees and Governance Bodies", duration: "25 min", type: "video", status: "completed" },
        { id: "l-1-8", title: "Information Technology in Business", duration: "28 min", type: "video", status: "completed" },
        { id: "l-1-9", title: "Reading: Case Studies", duration: "20 min", type: "reading", status: "completed" },
        { id: "l-1-10", title: "Module 1 Assignment", duration: "45 min", type: "assignment", status: "completed" },
      ],
    },
    {
      id: "mod-2",
      title: "Stakeholders and External Environment",
      lessonsCount: 12,
      duration: "6h 10m",
      lessons: [
        { id: "l-2-1", title: "Identifying Stakeholders", duration: "30 min", type: "video", status: "completed" },
        { id: "l-2-2", title: "Stakeholder Mapping", duration: "28 min", type: "video", status: "completed" },
        { id: "l-2-3", title: "Stakeholder Analysis Frameworks", duration: "35 min", type: "video", status: "current" },
        { id: "l-2-4", title: "Conflict Resolution with Stakeholders", duration: "32 min", type: "video", status: "locked" },
        { id: "l-2-5", title: "External Environment: PESTEL Analysis", duration: "38 min", type: "video", status: "locked" },
        { id: "l-2-6", title: "Porter's Five Forces", duration: "30 min", type: "video", status: "locked" },
        { id: "l-2-7", title: "Reading: Environmental Scanning", duration: "18 min", type: "reading", status: "locked" },
        { id: "l-2-8", title: "Quiz: Stakeholders", duration: "10 min", type: "quiz", status: "locked" },
        { id: "l-2-9", title: "Competitive Advantage", duration: "28 min", type: "video", status: "locked" },
        { id: "l-2-10", title: "Market Analysis Techniques", duration: "25 min", type: "video", status: "locked" },
        { id: "l-2-11", title: "Reading: Industry Reports", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-2-12", title: "Module 2 Assignment", duration: "50 min", type: "assignment", status: "locked" },
      ],
    },
    {
      id: "mod-3",
      title: "Corporate Governance and Ethics",
      lessonsCount: 11,
      duration: "5h 45m",
      lessons: [
        { id: "l-3-1", title: "Principles of Corporate Governance", duration: "34 min", type: "video", status: "locked" },
        { id: "l-3-2", title: "Board Structures and Directors", duration: "28 min", type: "video", status: "locked" },
        { id: "l-3-3", title: "Internal Controls and Risk", duration: "32 min", type: "video", status: "locked" },
        { id: "l-3-4", title: "Ethical Theories and Frameworks", duration: "30 min", type: "video", status: "locked" },
        { id: "l-3-5", title: "Professional Ethics in Accounting", duration: "35 min", type: "video", status: "locked" },
        { id: "l-3-6", title: "Reading: Governance Codes", duration: "20 min", type: "reading", status: "locked" },
        { id: "l-3-7", title: "Quiz: Governance", duration: "10 min", type: "quiz", status: "locked" },
        { id: "l-3-8", title: "Social Responsibility", duration: "26 min", type: "video", status: "locked" },
        { id: "l-3-9", title: "Sustainability Reporting", duration: "28 min", type: "video", status: "locked" },
        { id: "l-3-10", title: "Reading: Ethics Case Studies", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-3-11", title: "Module 3 Assignment", duration: "50 min", type: "assignment", status: "locked" },
      ],
    },
    {
      id: "mod-4",
      title: "Accounting and Finance Function",
      lessonsCount: 10,
      duration: "5h 00m",
      lessons: [
        { id: "l-4-1", title: "Role of Accounting in Business", duration: "30 min", type: "video", status: "locked" },
        { id: "l-4-2", title: "Financial vs Management Accounting", duration: "28 min", type: "video", status: "locked" },
        { id: "l-4-3", title: "Financial Statements Overview", duration: "35 min", type: "video", status: "locked" },
        { id: "l-4-4", title: "Budgeting Fundamentals", duration: "32 min", type: "video", status: "locked" },
        { id: "l-4-5", title: "Internal Audit Function", duration: "28 min", type: "video", status: "locked" },
        { id: "l-4-6", title: "Reading: Accounting Standards", duration: "18 min", type: "reading", status: "locked" },
        { id: "l-4-7", title: "Quiz: Finance Function", duration: "10 min", type: "quiz", status: "locked" },
        { id: "l-4-8", title: "Financial Controls", duration: "25 min", type: "video", status: "locked" },
        { id: "l-4-9", title: "Reading: Regulatory Framework", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-4-10", title: "Module 4 Assignment", duration: "45 min", type: "assignment", status: "locked" },
      ],
    },
    {
      id: "mod-5",
      title: "Leadership and Management",
      lessonsCount: 11,
      duration: "5h 30m",
      lessons: [
        { id: "l-5-1", title: "Leadership Theories", duration: "32 min", type: "video", status: "locked" },
        { id: "l-5-2", title: "Management vs Leadership", duration: "26 min", type: "video", status: "locked" },
        { id: "l-5-3", title: "Motivation Theories", duration: "30 min", type: "video", status: "locked" },
        { id: "l-5-4", title: "Team Dynamics", duration: "28 min", type: "video", status: "locked" },
        { id: "l-5-5", title: "Communication in Organisations", duration: "25 min", type: "video", status: "locked" },
        { id: "l-5-6", title: "Decision Making Processes", duration: "30 min", type: "video", status: "locked" },
        { id: "l-5-7", title: "Reading: Leadership Case Studies", duration: "18 min", type: "reading", status: "locked" },
        { id: "l-5-8", title: "Quiz: Leadership", duration: "10 min", type: "quiz", status: "locked" },
        { id: "l-5-9", title: "Change Management", duration: "32 min", type: "video", status: "locked" },
        { id: "l-5-10", title: "Reading: Management Frameworks", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-5-11", title: "Module 5 Assignment", duration: "50 min", type: "assignment", status: "locked" },
      ],
    },
    {
      id: "mod-6",
      title: "Human Resource Management",
      lessonsCount: 10,
      duration: "4h 50m",
      lessons: [
        { id: "l-6-1", title: "HRM Functions and Strategy", duration: "30 min", type: "video", status: "locked" },
        { id: "l-6-2", title: "Recruitment and Selection", duration: "28 min", type: "video", status: "locked" },
        { id: "l-6-3", title: "Training and Development", duration: "25 min", type: "video", status: "locked" },
        { id: "l-6-4", title: "Performance Management", duration: "28 min", type: "video", status: "locked" },
        { id: "l-6-5", title: "Employee Relations", duration: "26 min", type: "video", status: "locked" },
        { id: "l-6-6", title: "Diversity and Inclusion", duration: "22 min", type: "video", status: "locked" },
        { id: "l-6-7", title: "Reading: Employment Law", duration: "18 min", type: "reading", status: "locked" },
        { id: "l-6-8", title: "Quiz: HRM", duration: "10 min", type: "quiz", status: "locked" },
        { id: "l-6-9", title: "Reading: HR Best Practices", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-6-10", title: "Module 6 Assignment", duration: "45 min", type: "assignment", status: "locked" },
      ],
    },
    {
      id: "mod-7",
      title: "Information Systems and Technology",
      lessonsCount: 11,
      duration: "5h 15m",
      lessons: [
        { id: "l-7-1", title: "Information Systems in Business", duration: "30 min", type: "video", status: "locked" },
        { id: "l-7-2", title: "Data and Information", duration: "26 min", type: "video", status: "locked" },
        { id: "l-7-3", title: "IT Controls and Security", duration: "32 min", type: "video", status: "locked" },
        { id: "l-7-4", title: "Cloud Computing and SaaS", duration: "28 min", type: "video", status: "locked" },
        { id: "l-7-5", title: "E-Business and E-Commerce", duration: "25 min", type: "video", status: "locked" },
        { id: "l-7-6", title: "Big Data and Analytics", duration: "30 min", type: "video", status: "locked" },
        { id: "l-7-7", title: "Reading: Digital Transformation", duration: "18 min", type: "reading", status: "locked" },
        { id: "l-7-8", title: "Quiz: Information Systems", duration: "10 min", type: "quiz", status: "locked" },
        { id: "l-7-9", title: "System Implementation", duration: "28 min", type: "video", status: "locked" },
        { id: "l-7-10", title: "Reading: IT Governance", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-7-11", title: "Module 7 Assignment", duration: "50 min", type: "assignment", status: "locked" },
      ],
    },
    {
      id: "mod-8",
      title: "Exam Preparation and Practice",
      lessonsCount: 11,
      duration: "4h 10m",
      lessons: [
        { id: "l-8-1", title: "Exam Technique and Strategy", duration: "25 min", type: "video", status: "locked" },
        { id: "l-8-2", title: "Key Topics Review", duration: "30 min", type: "video", status: "locked" },
        { id: "l-8-3", title: "Practice Exam 1", duration: "45 min", type: "quiz", status: "locked" },
        { id: "l-8-4", title: "Practice Exam 1 Review", duration: "20 min", type: "video", status: "locked" },
        { id: "l-8-5", title: "Practice Exam 2", duration: "45 min", type: "quiz", status: "locked" },
        { id: "l-8-6", title: "Practice Exam 2 Review", duration: "20 min", type: "video", status: "locked" },
        { id: "l-8-7", title: "Reading: Common Pitfalls", duration: "15 min", type: "reading", status: "locked" },
        { id: "l-8-8", title: "Time Management Tips", duration: "18 min", type: "video", status: "locked" },
        { id: "l-8-9", title: "Final Revision Checklist", duration: "12 min", type: "reading", status: "locked" },
        { id: "l-8-10", title: "Mock Exam (Full Paper)", duration: "60 min", type: "quiz", status: "locked" },
        { id: "l-8-11", title: "Course Completion Survey", duration: "5 min", type: "reading", status: "locked" },
      ],
    },
  ],
  reviewSummary: {
    averageRating: 4.7,
    totalReviews: 842,
    distribution: [
      { stars: 5, count: 520, percentage: 62 },
      { stars: 4, count: 210, percentage: 25 },
      { stars: 3, count: 72, percentage: 9 },
      { stars: 2, count: 28, percentage: 3 },
      { stars: 1, count: 12, percentage: 1 },
    ],
  },
  relatedCourses: [
    {
      id: "acca-f2-ma",
      title: "ACCA F2 — Management Accounting",
      thumbnail: "/placeholder-course.jpg",
      instructor: "Prof. James Carter",
      rating: 4.6,
      studentsCount: 1_820,
      duration: "38 hours",
      level: "Foundation",
    },
    {
      id: "acca-f3-fa",
      title: "ACCA F3 — Financial Accounting",
      thumbnail: "/placeholder-course.jpg",
      instructor: "Dr. Emily Brooks",
      rating: 4.8,
      studentsCount: 2_100,
      duration: "45 hours",
      level: "Foundation",
    },
    {
      id: "acca-f4-cl",
      title: "ACCA F4 — Corporate & Business Law",
      thumbnail: "/placeholder-course.jpg",
      instructor: "Dr. Sarah Mitchell",
      rating: 4.5,
      studentsCount: 1_450,
      duration: "36 hours",
      level: "Fundamentals",
    },
  ],
};
